// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "TotumComXL",
    defaultLocalization: "en",
    // Homebrew builds its bottles (djvulibre & co) for the current OS, so the bundled
    // dylibs carry minos=15.0 — declaring anything lower would promise a macOS the app
    // physically cannot start on. Use the string form: .v15 needs swift-tools 6.
    platforms: [.macOS("15.0")],
    products: [
        .executable(name: "TotumComXLApp", targets: ["TotumComXLApp"]),
        // Standalone DjVu reader bundled inside TotumComXL.app/Contents/Library.
        .executable(name: "FCXLDjVuViewer", targets: ["FCXLDjVuViewer"]),
        .executable(name: "FCXLMCPServer", targets: ["FCXLMCPServer"])
    ],
    dependencies: [
        .package(url: "https://github.com/migueldeicaza/SwiftTerm.git", from: "1.0.0")
    ],
    targets: [
        .target(
            name: "FCXLMinizip",
            path: "third_party/minizip-ng",
            sources: [
                "mz_crypt.c",
                // Apple CommonCrypto backs the AES: password-protected zips could not be READ
                // while MZ_ZIP_NO_ENCRYPTION was defined — the writer (libarchive) encrypted
                // them fine and this reader then answered MZ_SUPPORT_ERROR to the right
                // password.
                "mz_crypt_apple.c",
                "mz_os.c",
                "mz_os_posix.c",
                "mz_strm.c",
                "mz_strm_buf.c",
                "mz_strm_mem.c",
                "mz_strm_os_posix.c",
                "mz_strm_pkcrypt.c",
                "mz_strm_split.c",
                "mz_strm_wzaes.c",
                "mz_strm_zlib.c",
                "mz_zip.c",
                "mz_zip_rw.c"
            ],
            publicHeadersPath: ".",
            cSettings: [
                .define("HAVE_STDINT_H"),
                .define("HAVE_INTTYPES_H"),
                .define("HAVE_ZLIB"),
                .define("ZLIB_COMPAT"),
                .define("HAVE_WZAES"),
                .define("HAVE_PKCRYPT"),
                .define("_POSIX_C_SOURCE", to: "200809L"),
                .define("_BSD_SOURCE"),
                .define("_DEFAULT_SOURCE"),
                .define("_DARWIN_C_SOURCE")
            ],
            linkerSettings: [
                .linkedLibrary("z"),
                .linkedFramework("Security")
            ]
        ),
        .target(
            name: "FCXLNTFS",
            path: "third_party/ntfs-3g",
            exclude: ["ntfs-3g"],
            sources: [
                "acls.c", "attrib.c", "attrlist.c", "bitmap.c", "bootsect.c",
                "cache.c", "collate.c", "compat.c", "compress.c", "debug.c",
                "device.c", "dir.c", "ea.c", "efs.c", "index.c", "inode.c",
                "ioctl.c", "lcnalloc.c", "logfile.c", "logging.c", "mft.c",
                "misc.c", "mst.c", "object_id.c", "realpath.c", "reparse.c",
                "runlist.c", "security.c", "unistr.c", "unix_io.c", "volume.c",
                "xattrs.c"
            ],
            publicHeadersPath: "public",
            cSettings: [
                .define("HAVE_CONFIG_H"),
                .define("_DARWIN_C_SOURCE"),
                .headerSearchPath("."),
                .headerSearchPath("ntfs-3g")
            ]
        ),
        .target(
            name: "FCXLScrypt",
            path: "crypto",
            sources: ["scrypt.c"],
            publicHeadersPath: "include",
            cSettings: [
                // The whole point of this target: the Salsa20/8 core must run optimised
                // even in debug builds, or unlocking an age file takes ages, literally.
                .unsafeFlags(["-O2"])
            ]
        ),
        .target(
            name: "FCXLCore",
            dependencies: ["FCXLMinizip", "FCXLNTFS"],
            path: "core",
            sources: ["src"],
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .headerSearchPath("../third_party/minizip-ng"),
                .headerSearchPath("../third_party/ntfs-3g"),
                .unsafeFlags([
                    "-I/opt/homebrew/opt/libarchive/include",
                    "-I/usr/local/opt/libarchive/include",
                    "-I/opt/homebrew/opt/libssh2/include",
                    "-I/usr/local/opt/libssh2/include"
                ])
            ],
            linkerSettings: [
                .linkedFramework("CoreServices"),
                .linkedLibrary("archive"),
                .linkedLibrary("curl"),
                .linkedLibrary("ssh2"),
                .unsafeFlags([
                    // Homebrew's libarchive is keg-only — it never lands in /opt/homebrew/lib.
                    // Without these the linker silently falls back to the SYSTEM libarchive,
                    // which was built without zstd/lz4 and "supports" them by spawning external
                    // programs the user may not have. The headers already came from this keg;
                    // compiling against 3.8 and linking 3.5 is exactly how that stayed hidden.
                    "-L/opt/homebrew/opt/libarchive/lib",
                    "-L/usr/local/opt/libarchive/lib",
                    "-L/opt/homebrew/opt/libssh2/lib",
                    "-L/usr/local/opt/libssh2/lib"
                ])
            ]
        ),
        .target(
            name: "FCXLBridgeObjC",
            dependencies: ["FCXLCore"],
            path: "bridge",
            sources: [
                "src/FCXLFileSystemBridge.mm",
                "src/FCXLSearchBridge.mm",
                "src/FCXLArchiveBridge.mm",
                "src/FCXLCompareBridge.mm",
                "src/FCXLToolsBridge.mm",
                "src/FCXLNTFSBridge.mm",
                "src/FCXLWatcherBridge.mm",
                "src/FCXLNetworkBridge.mm",
                "src/FCXLDjVuBridge.mm"
            ],
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .headerSearchPath("../core/include"),
                .headerSearchPath("../third_party/ntfs-3g"),
                .unsafeFlags([
                    "-I/opt/homebrew/include"
                ])
            ],
            linkerSettings: [
                .linkedFramework("Foundation"),
                .linkedFramework("Security"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("AppKit"),
                .linkedLibrary("djvulibre"),
                .unsafeFlags([
                    "-L/opt/homebrew/lib"
                ])
            ]
        ),
        // Shared DjVu page renderer — one implementation for the commander's F3 viewer and
        // the standalone reader, so an optimisation to one can never miss the other.
        .target(
            name: "FCXLDjVuUI",
            dependencies: ["FCXLBridgeObjC"],
            path: "djvuui"
        ),
        // The wire shared by the commander and the MCP bridge — one definition, so the two
        // can never disagree about what a message looks like.
        .target(
            name: "FCXLControlProtocol",
            path: "controlprotocol"
        ),
        // The MCP bridge: speaks JSON-RPC on stdin/stdout, forwards to the commander's socket.
        .executableTarget(
            name: "FCXLMCPServer",
            dependencies: ["FCXLControlProtocol"],
            path: "mcpserver"
        ),
        // Small standalone reader — shares the DjVu decoder bridge with the commander,
        // owns only its window. Ships inside the commander's bundle.
        .executableTarget(
            name: "FCXLDjVuViewer",
            dependencies: ["FCXLBridgeObjC", "FCXLDjVuUI"],
            path: "djvuviewer"
        ),
        .executableTarget(
            name: "TotumComXLApp",
            dependencies: ["FCXLBridgeObjC", "FCXLDjVuUI", "SwiftTerm", "FCXLControlProtocol", "FCXLScrypt"],
            path: "app/TotumComXL",
            sources: [
                "App/AppDelegate.swift",
                "App/TotumComXLApp.swift",
                "Models/FileItem.swift",
                "Models/PanelTab.swift",
                "Models/PosixPermissions.swift",
                "Models/QueuedOperation.swift",
                "Models/RemoteConnection.swift",
                "Models/RemoteSession.swift",
                "Services/CoreBridgeService.swift",
                "Services/SpotlightQueryBuilder.swift",
                "Services/SpotlightSearchService.swift",
                "Services/CoreErrorCode.swift",
                "Services/ExternalTerminalService.swift",
                "Services/DefaultApplicationService.swift",
                "Services/ControlServer.swift",
                "Services/DropStackStore.swift",
                "Services/AppUninstaller.swift",
                "Services/AppIconCache.swift",
                "Services/DXFDocument.swift",
                "Services/DiskImageOpenMode.swift",
                "Services/XattrInspector.swift",
                "Services/DarwinFileOperations.swift",
                "Services/FinderTagService.swift",
                "Services/GitStatusService.swift",
                "Services/PhotoMetadataService.swift",
                "Services/ImageConversionService.swift",
                "Services/PDFEditService.swift",
                "Services/VaultService.swift",
                "Services/CloudStatusService.swift",
                "Services/AgeCrypt.swift",
                "Services/FolderRules.swift",
                "Services/TextRecognitionService.swift",
                "Services/CustomFolderIconService.swift",
                "Services/CommandRegistry.swift",
                "Services/Book/BookDocument.swift",
                "Services/Book/FB2Parser.swift",
                "Services/Book/FB2Delegates.swift",
                "Services/Book/EPUBParser.swift",
                "Services/Book/BookLoader.swift",
                "Services/ReaderMarks.swift",
                "Services/DialogService.swift",
                "Services/TrashService.swift",
                "Services/FolderSizeCache.swift",
                "Services/EditorWindowManager.swift",
                "Services/ExternalOpenService.swift",
                "Services/FavoriteFolders.swift",
                "Services/FKeyAvailability.swift",
                "Services/ArchivePasswords.swift",
                "Services/MaskPresets.swift",
                "Services/UndoJournal.swift",
                "Services/FileOperationsService+Undo.swift",
                "Services/FileDiffService.swift",
                "Services/FileOperationsService.swift",
                "Services/PostScriptRenderer.swift",
                "Services/OperationProgressReporter.swift",
                "Services/OperationQueueService.swift",
                "Services/KeychainService.swift",
                "Services/Monitor/SystemMonitorService.swift",
                "Services/MultiRename/RenameRule.swift",
                "Services/MultiRename/RenameMaskEngine.swift",
                "Services/MultiRename/RenameExecutionPlanner.swift",
                "Services/MultiRename/RenamePresetStore.swift",
                "Services/Network/RemoteFileSystemProtocol.swift",
                "Services/Network/ConnectionManagerService.swift",
                "Services/Network/RemoteSessionRegistry.swift",
                "Services/Network/WebDAVRemoteFileSystem.swift",
                "Services/Network/AWSSignatureV4.swift",
                "Services/Network/S3RemoteFileSystem.swift",
                "Services/Network/RcloneDaemon.swift",
                "Services/Network/RcloneRemoteFileSystem.swift",
                "Services/Network/RcloneCloudSetup.swift",
                "Services/Network/RemoteFileCache.swift",
                "Services/Network/RemoteEditWatcher.swift",
                "Services/Network/RemoteLogin.swift",
                "Services/Network/FTPRemoteFileSystem.swift",
                "Services/Network/SFTPRemoteFileSystem.swift",
                "Services/Network/SMBRemoteFileSystem.swift",
                "Services/Network/RemoteTransferService.swift",
                "Services/Network/ResumableTransfer.swift",
                "Services/Network/TransferSpeedLimit.swift",
                "Services/FKeyModeManager.swift",
                "Services/VolumeKeys.swift",
                "Services/SystemShortcuts.swift",
                "Services/NSApplication+FKeyMode.swift",
                "Utils/Localization.swift",
                "Services/TunnelStore.swift",
                "Services/TunnelReorder.swift",
                "Helpers/ByteText.swift",
                "Helpers/PanelAppearanceSettings.swift",
                "Helpers/MacCapabilities.swift",
                "Helpers/FeatheredCursor.swift",
                "Helpers/LampFlicker.swift",
                "Helpers/ForceTouchSupport.swift",
                "Helpers/FolderIconRenderer.swift",
                "Helpers/DoubleClickSettings.swift",
                "Helpers/FileTypeColorPalette.swift",
                "Helpers/VolumeInterfaceDetector.swift",
                "Helpers/ContrastAppearance.swift",
                "Helpers/SwipeNavigation.swift",
                "Helpers/ContextMenuHelpers.swift",
                "Helpers/PreviewHelpers.swift",
                "Helpers/NotificationNames.swift",
                "ViewModels/PanelData.swift",
                "ViewModels/PanelState.swift",
                "ViewModels/PanelViewModel.swift",
                "ViewModels/MultiRenameViewModel.swift",
                "ViewModels/PanelViewModel+Remote.swift",
                "ViewModels/PanelTabsViewModel.swift",
                "ViewModels/OperationQueueViewModel.swift",
                "Views/Editor/EmbeddedEditorPanel.swift",
                "Views/Editor/MonacoEditorView.swift",
                "Views/Editor/MonacoEditorWindow.swift",
                "Views/Editor/RTFEditorPanel.swift",
                "Views/Viewer/EmbeddedViewerPanel.swift",
                "Views/Viewer/DXFView.swift",
                "Views/Viewer/PhotoInfoView.swift",
                "Views/Viewer/UnifiedFileViewer.swift",
                "Views/Viewer/BookReaderView.swift",
                "Views/Viewer/DjVuThumbnailStrip.swift",
                "Views/Viewer/PDFPageCache.swift",
                "Views/Viewer/PDFContextMenu.swift",
                "Views/Viewer/MarkdownPreview.swift",
                "Services/BookmarkNames.swift",
                "Services/FileColorRules.swift",
                "Views/Viewer/MediaPreviewView.swift",
                "Views/MainWindow/MainWindowController.swift",
                "Views/MainWindow/MainWindowController+MenuCommands.swift",
                "Views/MainWindow/DiskInfoView.swift",
                "Views/MainWindow/PanelSlot.swift",
                "Views/MainWindow/MainSplitViewController.swift",
                "Views/MainWindow/CenterDividerView.swift",
                "Views/MainWindow/TunnelIconPickerView.swift",
                "Views/MainWindow/TunnelContextMenus.swift",
                "Views/Help/HelpGuideView.swift",
                "Utils/MarkdownLite.swift",
                "Views/MainWindow/FooterBar.swift",
                "Views/Panel/ContextMenuBuilder.swift",
                "Views/Panel/ContextPopupMenu.swift",
                "Views/Panel/PanelViewController.swift",
                "Views/Panel/PanelBreadcrumbBar.swift",
                "Views/Panel/PanelStatusBar.swift",
                "Views/Panel/PanelVolumeBar.swift",
                "Views/Panel/FileListRowView.swift",
                "Views/Panel/FileListBriefView.swift",
                "Views/Panel/FileListThumbnailsView.swift",
                "Views/Panel/SortBarView.swift",
                "Views/Panel/GitBadgeChip.swift",
                "Views/Panel/DragStackImage.swift",
                "Views/Panel/MarqueeTextField.swift",
                "Views/Panel/InlineRenameLook.swift",
                "Views/Panel/QuickFilterBubble.swift",
                "Views/Panel/QuickFilterActionsPanel.swift",
                "Views/Panel/ColumnResizeHandle.swift",
                "Views/Dialogs/PackDialogController.swift",
                "Views/Dialogs/FolderRulesApplyView.swift",
                "Views/Dialogs/FolderRulesEditorView.swift",
                "Views/Dialogs/TextRecognitionDialogView.swift",
                "Views/Dialogs/CleanMetadataDialogView.swift",
                "Views/Dialogs/ImageConvertDialogView.swift",
                "Views/Dialogs/PDFEditDialogView.swift",
                "Views/Dialogs/VaultCreateDialogView.swift",
                "Views/Dialogs/AgeEncryptDialogView.swift",
                "Views/Dialogs/FCXLDialogKit.swift",
                "Views/Dialogs/OpenWithDialogView.swift",
                "Views/Dialogs/FileDiffDialogView.swift",
                "Views/Dialogs/FCXLMessageDialog.swift",
                "Views/Dialogs/FCXLProgressBar.swift",
                "Views/Dialogs/CopyMoveDialogView.swift",
                "Views/Dialogs/ArchiveDialogViews.swift",
                "Views/Help/HelpWindowView.swift",
                "Views/Dialogs/CommandPaletteView.swift",
                "Views/Dialogs/ChecksumDialogView.swift",
                "Views/Dialogs/FileSplitDialogView.swift",
                "Views/Dialogs/DirectoryCompareDialogView.swift",
                "Views/Dialogs/MaskSelectionDialogView.swift",
                "Views/Dialogs/ConflictDialogView.swift",
                "Views/Dialogs/FilePropertiesDialogView.swift",
                "Views/Dialogs/PermissionsGridView.swift",
                "Views/Dialogs/ChangeAttributesDialogView.swift",
                "Views/Dialogs/UninstallDialogView.swift",
                "Views/Settings/SettingsSection.swift",
                "Views/Settings/SettingsWindowAnimator.swift",
                "Views/Settings/SettingsDetailView.swift",
                "Views/Settings/SettingsSidebar.swift",
                "Views/Settings/SettingsRootView.swift",
                "Views/Settings/FCXLColorPicker.swift",
                "Views/Settings/CursorMaskEditorView.swift",
                "Views/Settings/Sections/SettingsGeneralView.swift",
                "Views/Settings/Sections/SettingsKeysView.swift",
                "Views/Settings/Sections/SettingsTerminalView.swift",
                "Views/Settings/Sections/SettingsListView.swift",
                "Views/Settings/Sections/SettingsAboutView.swift",
                "Views/Settings/Sections/SettingsColorsView.swift",
                "Views/Settings/Sections/SettingsFileColorsView.swift",
                "Views/Settings/Sections/SettingsCursorView.swift",
                "Views/Settings/Sections/SettingsFoldersView.swift",
                "Views/Settings/Sections/SettingsFontView.swift",
                "Views/Settings/Sections/SettingsTabsView.swift",
                "Views/Settings/Sections/SettingsDividerView.swift",
                "Views/Settings/Sections/SettingsContextMenuView.swift",
                "Views/Settings/Sections/SettingsNetworkNTFSView.swift",
                "Services/FileClipboard.swift",
                "Views/Common/NetworkMenuContent.swift",
                "Views/Network/ConnectionManagerView.swift",
                "Views/Network/NewConnectionDialogView.swift",
                "Views/Network/ConnectNetworkDriveView.swift",
                "Views/Network/NetworkBrowseBanner.swift",
                "Views/Network/NetworkAuthDialogView.swift",
                "Services/Network/NetworkBrowserService.swift",
                "Services/Network/LANScanner.swift",
                "Services/Network/LANDiscovery.swift",
                "Services/Network/LocalNetworkPermission.swift",
                "Services/Network/NetworkMountInfo.swift",
                "Views/Tabs/PanelTabsBarView.swift",
                "Views/Tabs/TabChipView.swift",
                "Views/Common/OperationQueuePanel.swift",
                "Views/Common/SharePanelHint.swift",
                "Views/Common/QueueOperationsBar.swift",
                "Views/Common/AccentMenuItem.swift",


                "Views/Search/AdvancedSearchView.swift",
                "Views/Search/SearchResultsTable.swift",

                "Views/Monitor/SystemMonitorView.swift",
                "Views/Monitor/ProcessInspectorDialogView.swift",
                "Views/MultiRename/RenamePreviewTable.swift",
                "Views/MultiRename/MultiRenameView.swift",
                "Views/MultiRename/MultiRenameWindow.swift",

                "Services/NTFSSessionManager.swift",
                "Services/NTFSPasswordStore.swift",
                "Services/Network/NetworkCredentialStore.swift",
                "Services/CursorMaskStore.swift",
                "Services/ContextMenuLayout.swift",
                "Services/ToolbarLook.swift",
                "Services/WindowLaunchMode.swift",
                "Services/AppIdentity.swift",
                "Services/UpdateChecker.swift",
                "Services/DefaultStyle.swift",
                "Services/ImageEditing.swift",
                "Services/DockProgressManager.swift",
                "Services/NotificationService.swift",
                "Services/OperationLogService.swift",
                "Views/Common/OperationLogView.swift",
                "Views/Terminal/TerminalView.swift"
            ],
            resources: [
                .process("Resources"),
                // Monaco must keep its folder layout: monaco-editor.html loads
                // `monaco/loader.min.js` and `monaco/vs/...` by relative path. `.process`
                // FLATTENS directory structure (that is why the local editor never loaded and
                // it silently fell back to the CDN), so ship the bundle verbatim with `.copy`.
                .copy("monaco")
            ],
            linkerSettings: [
                .linkedFramework("SwiftUI"),
                .linkedFramework("AppKit"),
                .linkedFramework("WebKit"),
                .linkedFramework("IOKit"),
                .linkedFramework("CoreServices"),
                .linkedFramework("AVKit"),
                .linkedFramework("PDFKit"),
                .linkedFramework("UserNotifications"),
                .linkedFramework("Security"),
                .linkedFramework("NetFS")
            ]
        ),
        .testTarget(
            name: "TotumComXLAppTests",
            dependencies: ["TotumComXLApp"],
            path: "app/TotumComXLTests",
            sources: [
                "ViewModelTests/PermanentDeleteTests.swift",
                "ViewModelTests/PackProgressTests.swift",
                "ViewModelTests/ArchiveFormatsTests.swift",
                "ViewModelTests/FolderSizeCacheTests.swift",
                "ViewModelTests/EmptyFolderSizeTests.swift",
                "ViewModelTests/SpaceSwitchFocusTests.swift",
                "ViewModelTests/TrashPanelTests.swift",
                "ViewModelTests/VolumeInterfaceTests.swift",
                "ViewModelTests/MkdirTests.swift",
                "ViewModelTests/PostScriptRendererTests.swift",
                "ViewModelTests/PDFContextMenuTests.swift",
                "ViewModelTests/MarkdownPreviewTests.swift",
                "ViewModelTests/FolderRulesEditorTests.swift",
                "ViewModelTests/ToolbarLookTests.swift",
                "ViewModelTests/WindowLaunchModeTests.swift",
                "ViewModelTests/AppIdentityTests.swift",
                "ViewModelTests/UpdateCheckerTests.swift",
                "ViewModelTests/DefaultStyleTests.swift",
                "ViewModelTests/ImageEditingTests.swift",
                "ViewModelTests/LocalNetworkPermissionTests.swift",
                "ViewModelTests/QueueIconStateTests.swift",
                "ViewModelTests/ProgressBarTests.swift",
                "ViewModelTests/ContrastAppearanceTests.swift",
                "ViewModelTests/SwipeNavigationTests.swift",
                "ViewModelTests/PanelClickFocusTests.swift",
                "ViewModelTests/VolumeBlockerTests.swift",
                "ViewModelTests/NetworkAuthTests.swift",
                "ViewModelTests/VolumeBarNetworkTests.swift",
                "ViewModelTests/VolumeBarActiveDiskTests.swift",
                "ViewModelTests/VolumeBarLabelTests.swift",
                "ViewModelTests/AlternateRowsTests.swift",
                "ViewModelTests/CursorMaskTests.swift",
                "ViewModelTests/NetworkBrowserDedupTests.swift",
                "ViewModelTests/TrashServiceTests.swift",
                "ViewModelTests/OperationErrorReportingTests.swift",
                "ViewModelTests/PanelViewModelScrollTests.swift",
                "ViewModelTests/PanelViewModelContextMenuTests.swift",
                "ViewModelTests/PanelViewModelBriefNavigationTests.swift",
                "ViewModelTests/PanelViewModelSortingTests.swift",
                "ViewModelTests/FileListBriefViewTests.swift",
                "ViewModelTests/FileListThumbnailsViewTests.swift",
                "ViewModelTests/ThumbnailsCollectionViewTests.swift",
                "ViewModelTests/DoubleClickSettingsTests.swift",
                "ViewModelTests/PackDialogControllerTests.swift",
                "ViewModelTests/AppKitMigrationTests.swift",
                "ViewModelTests/PanelStateTests.swift",
                "ViewModelTests/PanelDataTests.swift",
                "ViewModelTests/KeychainServiceTests.swift",
                "ViewModelTests/RemoteQueueIntegrationTests.swift",
                "ViewModelTests/FavoriteFoldersTests.swift",
                "ViewModelTests/FileDiffTests.swift",
                "ViewModelTests/FileOperationsServiceTests.swift",
                "ViewModelTests/HardlinkCopyTests.swift",
                "ViewModelTests/AliasCreationTests.swift",
                "ViewModelTests/CursorOutlineTests.swift",
                "ViewModelTests/ForceTouchTests.swift",
                "ViewModelTests/ShareSessionTests.swift",
                "ViewModelTests/SendPackingTests.swift",
                "ViewModelTests/SharePanelEscapeTests.swift",
                "ViewModelTests/SharePanelHintTests.swift",
                "ViewModelTests/ShareSessionOwnershipTests.swift",
                "ViewModelTests/FileItemAndCopyNameTests.swift",
                "ViewModelTests/PanelAppearanceColorTests.swift",
                "ViewModelTests/QueuedOperationTests.swift",
                "ViewModelTests/FileSplitJoinTests.swift",
                "ViewModelTests/MarqueeTextFieldTests.swift",
                "ViewModelTests/FinderTagDotsTests.swift",
                "ViewModelTests/CustomFolderIconServiceTests.swift",
                "ViewModelTests/DirectoryStatsTests.swift",
                "ViewModelTests/QuickFilterTests.swift",
                "ViewModelTests/SelectionMaskTests.swift",
                "ViewModelTests/UndoTests.swift",
                "ViewModelTests/CommandMatcherTests.swift",
                "ViewModelTests/RenameMaskEngineTests.swift",
                "ViewModelTests/RenameExecutionPlannerTests.swift",
                "ViewModelTests/RenamePresetStoreTests.swift",
                "ViewModelTests/MultiRenameViewModelTests.swift",
                "ViewModelTests/MultiRenameBehaviorTests.swift",
                "ViewModelTests/RemoteConnectionTests.swift",
                "ViewModelTests/PanelTabTests.swift",
                "ViewModelTests/PanelTabsRestoreTests.swift",
                "ViewModelTests/CmdClickSelectionTests.swift",
                "ViewModelTests/PosixPermissionsTests.swift",
                "ViewModelTests/FileItemComputedTests.swift",
                "ViewModelTests/NetworkMountInfoCacheTests.swift",
                "ViewModelTests/RemoteLoginTests.swift",
                "ViewModelTests/FieldEchoTests.swift",
                "ViewModelTests/LANScannerBudgetTests.swift",
                "ViewModelTests/LANDiscoveryTests.swift",
                "ViewModelTests/PanelSlotTests.swift",
                "ViewModelTests/NetworkBrowseStatusTests.swift",
                "ViewModelTests/RemoteSessionTests.swift",
                "ViewModelTests/BranchViewTests.swift",
                "ViewModelTests/ColumnOrderTests.swift",
                "ViewModelTests/ExternalTerminalTests.swift",
                "ViewModelTests/DiskImageOpenModeTests.swift",
                "ViewModelTests/SpotlightQueryTests.swift",
                "ViewModelTests/NameCellEditingTests.swift",
                "ViewModelTests/SearchResultCapTests.swift",
                "ViewModelTests/DefaultApplicationTests.swift",
                "ViewModelTests/ControlServerTests.swift",
                "ViewModelTests/DropStackTests.swift",
                "ViewModelTests/AppUninstallerTests.swift",
                "ViewModelTests/AppIconCacheTests.swift",
                "ViewModelTests/DXFDocumentTests.swift",
                "ViewModelTests/DXFCanvasTests.swift",
                "ViewModelTests/GitStatusServiceTests.swift",
                "ViewModelTests/FolderRulesTests.swift",
                "ViewModelTests/TextRecognitionTests.swift",
                "ViewModelTests/PhotoMetadataTests.swift",
                "ViewModelTests/ImageConversionTests.swift",
                "ViewModelTests/PDFEditTests.swift",
                "ViewModelTests/VaultServiceTests.swift",
                "ViewModelTests/MessageDialogLayoutTests.swift",
                "ViewModelTests/AgeCryptTests.swift",
                "ViewModelTests/CloudStatusTests.swift",
                "ViewModelTests/BookReadingTests.swift",
                "ViewModelTests/FileColorRulesTests.swift",
                "ViewModelTests/AWSSignatureV4Tests.swift",
                "ViewModelTests/S3ListingTests.swift",
                "ViewModelTests/S3LiveTests.swift",
                "ViewModelTests/UploadTargetNameTests.swift",
                "ViewModelTests/RcloneLiveTests.swift",
                "ViewModelTests/RcloneRealTests.swift",
                "ViewModelTests/RemoteFileCacheTests.swift",
                "ViewModelTests/RemoteEditWatcherTests.swift",
                "ViewModelTests/CancelBoxTests.swift",
                "ViewModelTests/ByteTextTests.swift",
                "ViewModelTests/RemoteReconnectTests.swift",
                "ViewModelTests/RemoteDeleteTests.swift",
                "ViewModelTests/RemoteNavigationRaceTests.swift",
                "ViewModelTests/ShelfNavigationTests.swift",
                "ViewModelTests/TunnelStoreTests.swift",
                "ViewModelTests/TunnelLookTests.swift",
                "ViewModelTests/TunnelContextMenuTests.swift",
                "ViewModelTests/TunnelSmallWindowTests.swift",
                "ViewModelTests/TunnelOverflowTests.swift",
                "ViewModelTests/ThemedMirrorTests.swift",
                "ViewModelTests/ContextMenuLayoutTests.swift",
                "ViewModelTests/TunnelReorderTests.swift",
                "ViewModelTests/MainMenuTests.swift",
                "ViewModelTests/MarkdownLiteTests.swift",
                "ViewModelTests/HelpGuideTests.swift",
                "ViewModelTests/LocalizationFilesTests.swift",
                "ViewModelTests/TabsBarLookTests.swift",
                "ViewModelTests/TunnelButtonLookTests.swift",
                "ViewModelTests/RemoteSessionRegistryTests.swift",
                "ViewModelTests/InlineRenameLookTests.swift",
                "ViewModelTests/SmbutilListingTests.swift",
                "ViewModelTests/VolumeKeysTests.swift",
                "ViewModelTests/SystemShortcutsTests.swift",
                "ViewModelTests/GitBadgeLookTests.swift",
                "ViewModelTests/ArchiveExitTests.swift",
                "ViewModelTests/ArchiveOpenFailureTests.swift",
                "ViewModelTests/SelectedNameColorTests.swift",
                "ViewModelTests/OperationTargetsSettingTests.swift",
                "ViewModelTests/WindowPlacementTests.swift",
                "ViewModelTests/NewConnectionLookTests.swift",
                "ViewModelTests/RcloneRulesTests.swift",
                "ViewModelTests/ContextMenuShapeTests.swift",
                "ViewModelTests/ArchiveExtractProgressTests.swift",
                "ViewModelTests/HelpTopicsTests.swift",
                "ViewModelTests/XattrInspectorTests.swift",
                "ViewModelTests/StatusNumbersTests.swift",
                "ViewModelTests/ChangeAttributesTests.swift",
                "ViewModelTests/ResumableTransferTests.swift",
                "ViewModelTests/ResumeFailedTransferTests.swift",
                "ViewModelTests/LocalizationTests.swift",
                "ViewModelTests/DarwinFileOperationsTests.swift",
            ]
        )
    ],
    cxxLanguageStandard: .cxx20
)
